### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by Stanzilla** [hschne/fzf-git#3]
Hey there, just wanted to ask if you still maintain this project or if you can recommend a different implementation that does the same? Thanks!

**Comment by hschne** [comment]
I'm not actively developing this project, mainly because I am rather unhappy with the existing completion functions/widgets that fzf provides. I'm planning to create a similar project to this one (with extended functionalities) in the near future though - but no promises ;) 

If you have any specific features you would like to see I would gladly hear them though!

**Comment by Stanzilla** [comment]
Ah, cool! Nope, just getting started with customizing my completion stuff and just want to avoid using stuff that is no longer getting updates, thank you! :)
